### ISSUE TITLE
ABCD all unique part numbers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#12]
Same connectors means confused humans, let's have unique ABCD connectors please

**Comment by rusefillc** [comment]
@Qwerty-OFF а ещё мне бы номера ответных разъёмов на провода, я их готов заказывать

**Comment by Qwerty-OFF** [comment]
39012060
39012080
39012160
39012180
39012200
Вместо последнего "0" можно "5"
39000038 на провод 18-24 AWG
