### ISSUE TITLE
silkscreen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#13]
* [x] https://rusefi.com/s/uaefu
* [x] rev A
* [x] "always looking for C/C++..."
* [x] spell out "WBO SWD"
* [x] spell out "USB" next to 5 pin USB

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/uaefi/assets/4116383/afa4cdf1-67db-4861-b535-9cccaa626a8b)

![image](https://github.com/rusefi/uaefi/assets/4116383/46693df0-9b2f-4ea9-bcc1-811c5c5985cb)

**Comment by rusefillc** [comment]
давай или добавим слово "wbo" рядом с swd или заменим?

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/uaefi/assets/4116383/12dc1f37-4c5e-44ea-8325-909b2774c1b7)
Нужен QR?

**Comment by rusefillc** [comment]
> Нужен QR?

Да нет наверное
