### ISSUE TITLE
fun ticket: STM32F407VGT6 price and availability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#2]
https://jlcpcb.com/partdetail/Stmicroelectronics-STM32F407VGT6/C12345

![image](https://github.com/rusefi/uaefi/assets/48498823/3a9f82a7-ed81-4294-86e8-48b7cd05ee92)

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/19

**Comment by rusefillc** [comment]
What's going on? stm32 cheaper than Geehy?!

https://jlcpcb.com/partdetail/Geehy-APM32F407VGT6/C2990873


well yes stock goes down let me go grab some more :)

![image](https://github.com/rusefi/uaefi/assets/48498823/c5fa8272-a5d3-4396-9bb9-c67740582323)

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/uaefi/assets/5685108/10efcccc-6583-4c40-bae9-912bf9304cbc)

After 30pc it IS cheaper

Worth it is a different story

**Comment by rusefillc** [comment]
![Screenshot_20230921_091048_Chrome](https://github.com/rusefi/uaefi/assets/48498823/a064bacf-cd3b-4289-ad81-0bb9c94dd362)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/uaefi/assets/48498823/2ddc9c28-8d0c-45a0-b5df-a957b96f7599)

**Comment by rusefillc** [comment]
they got more!

![image](https://github.com/rusefi/uaefi/assets/48498823/aa0b2d72-9b92-4a87-ba79-16aefc782fc8)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/uaefi/assets/48498823/5819c7d4-4d6d-4fe1-b5fe-e22661ae0cd6)

**Comment by rusefillc** [comment]
Looks like $4 is the official reality these days

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/uaefi/assets/48498823/5ef44bd5-c8f5-4cc6-a118-5b3063f6c0db)
