### ISSUE TITLE
диагностика КЗ 5в

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#20]
этот пин про диагностику? у нас есть место добавить для него трассу в один из свободных пинов?

![image](https://github.com/rusefi/uaefi/assets/48498823/ea327cb9-43db-49f1-83c9-c60f01f843e3)

**Comment by Qwerty-OFF** [comment]
Про диагностику. Свободный пин перестанет быть via. Через джампер?

**Comment by rusefillc** [comment]
> Про диагностику. Свободный пин перестанет быть via. Через джампер?

Да
