### ISSUE TITLE
ISL9V3040 status

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#30]
```
The IGBT called out in the Gerber, ISL9V3040D3S, is absolute and no longer sold/manufactured. I would assume finding one with the same properties and package size would make for a good replacement? Or is there another PN recommendation?
```

ISL9V3040S3ST seems active is that the replacement? either way let's have a not dead part on the schematics (not just BOM)

**Comment by Qwerty-OFF** [comment]
ISL9V3040**S**3ST это большой корпус
ISL9V3040**D**3ST нам подходит, напишу его на схеме
ISL9V3040D3ST-F085C если что тоже
