### ISSUE TITLE
how about VNL5160 for Qx

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#31]
VNL5160 (single not VNLD) be an option for Qx?

https://jlcpcb.com/partdetail/Stmicroelectronics-VNL5160N3TRE/C262999

**Comment by rusefillc** [comment]
might end up being cheapest option?

**Comment by Qwerty-OFF** [comment]
VNL5160 may not be opened by STM32
![image](https://github.com/rusefi/uaefi/assets/4116383/8580a1ce-4d21-4b99-bb83-49ff7b6c7dd5)

**Comment by rusefillc** [comment]
https://github.com/mck1117/wideband/pull/173#issuecomment-1347375876
