### ISSUE TITLE
Add 2.54mm header while not changing board size

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#34]
Can not increase board size so would have to do strange stuff - this is all about soldering two boards together with minimal manual effort

technically could be all single 2.54mm pins
technically some pads we can leave without 2.54mm if totally impossible to add

**Comment by rusefillc** [comment]
@Ringenium suggests https://www.lcsc.com/product-detail/Connector-Accessories_JST-RT-01T-1-0B-LF_C265321.html instead

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/uaefi/assets/48498823/90469723-e473-4089-978d-91f291b40208)

**Comment by Ringenium** [comment]
@rusefillc  добавлено
