### ISSUE TITLE
cost reduction ideas

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#35]
J2/J3/J4/J5 alternatives same as J10

![image](https://github.com/rusefi/uaefi/assets/48498823/d54060cb-a650-4044-b833-f9d01aef4233)

**Comment by rusefillc** [comment]
@Qwerty-OFF do we care to use specifically C32677 for "19V 13.3V 12V SOT-23(TO-236) TVS ROHS"

оно basic но относительно дорогой. extended бывают сильно дешевле https://jlcpcb.com/partdetail/Onsemi-MMBZ20VALT1G%2FC153067#EC известный бренд, это подходит?

**Comment by rusefillc** [comment]
@Qwerty-OFF усилитель это важно, мы никому тут не верим?

![image](https://github.com/rusefi/uaefi/assets/48498823/c470963b-f86c-46b4-9878-468fed300dae)

**Comment by Qwerty-OFF** [comment]
PSM712 можно поменять на другой extended дешёвый PSM712. Твой вариант не подходит

**Comment by Qwerty-OFF** [comment]
Усилитель китайский китай брать не стоит, возможно искать какие-то аналоги от нормальных производителей дешевле

**Comment by rusefillc** [comment]
> Усилитель китайский китай брать не стоит, возможно искать какие-то аналоги от нормальных производителей дешевле

ну или https://github.com/rusefi/uaefi/issues/40
