### ISSUE TITLE
подписать рекомендованные назначения пинов синим

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#37]
не меняя названия сетей на схеме хочется где-то голубым добавить комментарий про рекомендации

Fan Relay https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=b&pin=B8 
Main Relay https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=b&pin=B9
Fuel Pump Relay https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=b&pin=B16
Idle Air Valve https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=b&pin=B18

примерно вот так
![image](https://github.com/rusefi/uaefi/assets/48498823/7cfbd660-0875-442c-81c7-5c7290d70503)

**Comment by rusefillc** [comment]
вторая половина https://github.com/rusefi/kicad6-libraries/issues/15

**Comment by rusefillc** [comment]
@Ringenium 
VVT1 https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=b&pin=B7
CAM1 https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=c&pin=C5
CAM2 https://rusefi.com/docs/pinouts/hellen/uaefi/?connector=c&pin=C6

**Comment by Ringenium** [comment]
Все добавил в компонент
