### ISSUE TITLE
via for dc2 control lines

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#39]
for cases when we need less DC but more GPIO let's have vias on DC2_PWM and DC2_DIR

i guess if we are doing DC2 can we _also_ do same on DC1 as long as not a major effort?

**Comment by Qwerty-OFF** [comment]
Added for both
![image](https://github.com/rusefi/uaefi/assets/4116383/e63ddb4e-685b-46f6-a90c-88a7cadb2aa2)
