### ISSUE TITLE
fab B U107 orientation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#46]
"LPS22HBTR","U107","HLGA-10L","C94049"

Since we are not so sure about the polarities of the components U107 are correct or not. Could you please kindly check if the polarities and placements of the components are correct in the below picture? Is it okay to proceed with production?

**Comment by Qwerty-OFF** [comment]
Correct
<img width="350" alt="image" src="https://github.com/rusefi/uaefi/assets/4116383/36a95157-5073-4b71-87f2-a12dc8f469b7">

**Comment by rusefillc** [comment]
@Qwerty-OFF they have asked on rev C
