### ISSUE TITLE
rename VR networks

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#50]
No copper change but let's make schematics more readable

![image](https://github.com/rusefi/uaefi/assets/48498823/25688544-8d46-494c-9da0-de8d2abfd6bd)

vr_1_threshold also looses "_1" since it's the only threshold?

**Comment by rusefillc** [comment]
Dup #47

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/uaefi/assets/4116383/b1e5aba8-71d7-4c0b-a9d0-a64185ea245a)
