### ISSUE TITLE
Add EGT passives into BOM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#53]
EGT caps/resistors are probably just a couple of cents? Let's add into BOM

**Comment by Qwerty-OFF** [comment]
Only the NUP2105L and MAX31855KASA are DNP now

**Comment by rusefillc** [comment]
А можно мы их выключим через replace? мне тогда сильно проще включить при желании

**Comment by Qwerty-OFF** [comment]
Да

**Comment by rusefillc** [comment]
@Qwerty-OFF какова роль NUP2105L - будет ли без него что-то работать?

если есть шанс жить без него - можно мы на схему что-нить про это напишем?

**Comment by rusefillc** [comment]
@dron0gus says ``Элемент защиты. Работать будет.``
