### ISSUE TITLE
make on-board MAP sensor pinout more obvious

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#54]
a talented individual can solder mpx4250 more than one way, we need some clarification note

![image](https://github.com/rusefi/uaefi/assets/48498823/d3a47a1e-3963-42fe-b0b6-9d244f50bb96)

**Comment by ggurov** [comment]
![image](https://github.com/rusefi/uaefi/assets/2112173/c9439597-e965-4356-8b91-8f383832c16a)

**Comment by rusefillc** [comment]
I am tired and slow

Just realized that we have a drawing of the vacuum line outlet which tells how to position, not sure if any clarification is needed on top of that.

TIL about notch on the first pin!

**Comment by ggurov** [comment]
should mark the input pin. the drawing of the vacuum line did not help. i went for the multimeter to and started tracing stuff. maybe put PC1 next to that through hole for the notch, or  put "notch" next to it as well.

**Comment by Qwerty-OFF** [comment]
Added pin numbers
![image](https://github.com/rusefi/uaefi/assets/4116383/981d8985-94be-4d64-a4da-bdcf4f74ea3a)
