### ISSUE TITLE
pad for resistor between VR lines

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#57]
* Do we have a pad to mount a resistor between both VR lines? 
* is it easy to use?
* do we have a note on the schematics explaining, similar to Frankenso?

**Comment by rusefillc** [comment]
@Qwerty-OFF do we already have similar resistor between lines anywhere?

**Comment by rusefillc** [comment]
max9924 already has it just needs documentation https://github.com/andreika-git/hellen-one/issues/374

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/uaefi/assets/4116383/668bf35c-cc34-43f9-99af-9546b9aead3f)

https://github.com/andreika-git/hellen-one/commit/21de8c2cf88dabbff60d48988fd028638cbae64e
https://github.com/andreika-git/hellen-one/commit/48b12a8b670ce0aafff5a7f58c853033d809f7e2
