### ISSUE TITLE
happypath REV C ordering wrong orientation elements

### ISSUE THREAD

**Issue by ggurov** [rusefi/uaefi#64]
When ordering from JLC, two ICs appear rotated in the preview:

![image](https://github.com/rusefi/uaefi/assets/2112173/0fbe97d5-d632-4a99-a208-b9449e423092)

![image](https://github.com/rusefi/uaefi/assets/2112173/ce52a0cc-5e83-428d-9e86-4ffb04b1f6b6)

![image](https://github.com/rusefi/uaefi/assets/2112173/a3c5ffb0-1c85-4de5-a795-3e656c8bcf22)

**Comment by rusefillc** [comment]
https://github.com/rusefi/uaefi/?tab=readme-ov-file#q-ive-place-an-order-with-jlcpcb-and-i-see-scary-looking-wrong-orientation

https://github.com/andreika-git/hellen-one/issues/294
