### ISSUE TITLE
improve "real hot VR" explanation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#65]
Frankenso offers 5K default

![image](https://github.com/rusefi/uaefi/assets/48498823/ba8e716d-d7b0-48a0-824a-19516604eb85)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/user-attachments/assets/70f505d9-cde9-4884-8a26-4f9a71c83567)
Что-то более понятное чем это нужно написать?
