### ISSUE TITLE
how to i hook up logic analyzer to both VRs?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#66]
We have amazing "cam" and "crank" vias on MM100 but looks like these are routed into random hall/button inputs?

Q1: where are the best spots to solder a wire for logic analyzer?
Q2: do we have space on the board to add vias?

![image](https://github.com/user-attachments/assets/b5ac7e7b-9e73-4780-8c45-eb6587f65488)

**Comment by rusefillc** [comment]
![WhatsApp Image 2024-08-10 at 20 29 50_d12a5663](https://github.com/user-attachments/assets/e46da048-ba32-4c88-978d-c7751d98727f)

![WhatsApp Image 2024-08-10 at 20 29 51_fcef7643](https://github.com/user-attachments/assets/7496720a-786e-46b3-becf-4de1053beb5e)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/user-attachments/assets/62c1da83-a5cb-4efe-b62e-a75a28587389)
