### ISSUE TITLE
readability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/uaefi#9]
it's not clear if "2A capable" applies to LS or DC or both

![image](https://github.com/rusefi/uaefi/assets/48498823/71dadd56-6aab-4be0-978d-13bd0598373f)

same about "always hot" being a bit between things

![image](https://github.com/rusefi/uaefi/assets/48498823/7602aaed-e918-4f63-b47b-67c4619148c8)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/uaefi/assets/4116383/053ed6f1-a30d-44bd-ad24-6e3cb0538b10)
